### ISSUE TITLE
Incompatible with staudenmeir/eloquent-has-many-deep?

### ISSUE THREAD

**Issue by jurrevanderschaaf** [staudenmeir/laravel-merged-relations#14] opened 2023-02-18 16:07 UTC
Hello, I am already using staudenmeir/eloquent-has-many-deep relationships and wanted to use this package as well. However, I noticed these seem to be incompatible, am I correct?

staudenmeir/laravel-merged-relations: v1.5.2
staudenmeir/eloquent-has-many-deep: v1.17.1
Laravel: 9.46

When I'm trying to create a merged view with a relation which is defined using hasManyDeepFromRelations(), it uses the wrong 'base model'

In model "A":
```
public function c()
{
	return $this->hasManyDeepFromRelations($this->b(), (new B)->c());
}
```

Creating schema:
```
Schema::createMergeViewWithoutDuplicates(
        'all_cs',
        [(new A)->c()]
);
```

Results in:
```
CREATE OR REPLACE
ALGORITHM = UNDEFINED VIEW `all_cs` AS
select
    `cs`.`id` AS `id`,
    `cs`.`name` AS `name`,
    `cs`.`created_at` AS `created_at`,
    `cs`.`updated_at` AS `updated_at`,
    `bs`.`id` AS `laravel_foreign_key`,
    'App\\Models\\C' AS `laravel_model`,
    '' AS `laravel_placeholders`,
    '' AS `laravel_with`
from
...
```

### Expected result:
I was expecting it would do
``` `as`.`id` AS `laravel_foreign_key` ```
instead of
``` `bs`.`id` AS `laravel_foreign_key` ```

It does create the correct query to query using a B model. It seems to skip the first level (from what I would expect, at least).

**Comment by staudenmeir** [comment] 2023-02-19 12:58
Hi @jurrevanderschaaf,
Please share your actual relationships and the actual SQL that `Schema::createMergeViewWithoutDuplicates()` executes.

**Comment by jurrevanderschaaf** [comment] 2023-02-19 16:54
Below are the actual relationships I have. I thought it would make it more readable to replace it with a, b and c.


In Ticket.php:
```
public function product()
{
    return $this->belongsTo(Product::class, 'product_id', 'id');
}
public function order()
{
    return $this->belongsTo(Order::class, 'order_id', 'id');
}
public function tags_via_products()
{
    return $this->hasManyDeepFromRelations($this->product(), (new Product)->tags());
}
public function tags_via_discount_types()
{
    return $this->hasManyDeepFromRelations($this->order(), (new Order)->discounts(), (new OrderDiscount)->discount_type(), (new DiscountType)->tags());
}
public function tags()
{
    return $this->mergedRelationWithModel(Tag::class, 'ticket__all_tags');
}
```

In Product.php:
```
public function tags()
{
    return $this->morphToMany(Tag::class, 'taggable');
}
```

In Order.php:
```
public function discounts()
{
    return $this->hasMany(OrderDiscount::class);
}
```

In OrderDiscount.php: 
```
public function discount_type()
{
    return $this->belongsTo(DiscountType::class);
}
```

In DiscountType.php:
```
public function tags()
{
    return $this->morphToMany(Tag::class, 'taggable');
}
```

Finally, the function
```
Staudenmeir\LaravelMergedRelations\Facades\Schema::createMergeViewWithoutDuplicates(
    'ticket__all_tags',
    [(new \App\Models\Ticket)->tags_via_products(), (new \App\Models\Ticket)->tags_via_discount_types()]
);
```

creates the following SQL:
```
create view `ticket__all_tags` as (
  select
    `tags`.`id`,
    `tags`.`user_id`,
    `tags`.`name`,
    `tags`.`created_at`,
    `tags`.`updated_at`,
    `products`.`id` as laravel_foreign_key,
    'App\\Models\\Tag' as laravel_model,
    '' as laravel_placeholders,
    '' as laravel_with
  from
    `tags`
    inner join `taggables` on `taggables`.`tag_id` = `tags`.`id`
    inner join `products` on `products`.`id` = `taggables`.`taggable_id`
  where
    `taggables`.`taggable_type` = 'App\\Models\\Product'
)
union
  (
    select
      `tags`.`id`,
      `tags`.`user_id`,
      `tags`.`name`,
      `tags`.`created_at`,
      `tags`.`updated_at`,
      `orders`.`id` as laravel_foreign_key,
      'App\\Models\\Tag' as laravel_model,
      '' as laravel_placeholders,
      '' as laravel_with
    from
      `tags`
      inner join `taggables` on `taggables`.`tag_id` = `tags`.`id`
      inner join `discount_types` on `discount_types`.`id` = `taggables`.`taggable_id`
      inner join `order_discounts` on `order_discounts`.`discount_type_id` = `discount_types`.`id`
      inner join `orders` on `orders`.`id` = `order_discounts`.`order_id`
    where
      `taggables`.`taggable_type` = 'App\\Models\\DiscountType'
  )
```

**Comment by staudenmeir** [comment] 2023-03-03 23:04
Did you test the results of the merged relationship? `eloquent-has-many-deep` is supported and the queries look correct.

> It does create the correct query to query using a B model. It seems to skip the first level (from what I would expect, at least).

All native (and most third-party) relationships don't include the base table in the query, they start with the "next" table to improve performance.

**Comment by jurrevanderschaaf** [comment] 2023-03-04 17:07
Hi,
Yes, I tested the result of the merged relationship, it returns an empty result. The query performed on the database is:

```
select
  *
from
  `ticket__all_tags`
where
  `ticket__all_tags`.`laravel_foreign_key` in (14347)
```

Here, `14347` is the id of the model Ticket.
However, when I inspect the all rows in the view in DBeaver, I see `laravel_foreign_key` is filled with the ids of the models Product and DiscountType.

**Comment by staudenmeir** [comment] 2023-03-04 17:35
I know what the issue is, I'm working on a fix.

**Comment by ksschwab** [comment] 2023-06-05 19:43
Hello @staudenmeir, is there progress on a potential fix for this? Thanks.

**Comment by staudenmeir** [comment] 2023-06-10 15:44
I'm still working on the fix.

**Comment by Naoray** [comment] 2023-06-27 11:41
I might have encountered the same or a similar problem.

I have a `Customer` Model

```php
class Customer extends Model
{
  //…

  public function allTransactions(): MergedRelation
    {
        return $this->mergedRelationWithModel(Transaction::class, 'all_transactions');
    }

    public function transactions(): MorphMany
    {
        return $this->morphMany(Transaction::class, 'transactionable');
    }

    public function artistTransactions(): HasManyDeep
    {
        return $this->hasManyDeep(
            Transaction::class,
            [User::class, Artist::class],
            ['id', 'user_id', ['transactionable_type', 'transactionable_id']],
            ['user_id', 'id']
        );
    }
}
```

And I’ve created the merged view with

```php
        Schema::createMergeViewWithoutDuplicates(
            'all_transactions',
            [(new Customer)->transactions(), (new Customer)->artistTransactions()]
        );
```

When I call `$customer->allTransactions` I am only getting transactions that are directly related to the `Customer` (same result as calling `$customer->transactions`). Calling `$customer->artistTransactions` I receive a different set of results.

Is there any way I can support you in solving this issue @staudenmeir? Or can you point me to where the issue might be? I am happy to create a PR for this.

**Comment by staudenmeir** [comment] 2023-06-27 20:27
@Naoray Yeah, that's the same issue. Thanks for the offer, but I'm almost finished with the fix. I'll provide you with a branch to test it. What Laravel version are you using?

**Comment by Naoray** [comment] 2023-06-27 21:02
@staudenmeir the project I am working on is currently using laravel v9

**Comment by staudenmeir** [comment] 2023-06-29 05:03
I pushed a fix into the `has-many-deep-fix` branch. Replace the package's version constraint in your `composer.json` with `dev-has-many-deep-fix` and run `composer update staudenmeir/laravel-merged-relations`.

**Comment by Naoray** [comment] 2023-06-29 11:49
@staudenmeir that is working. 

Thank you @staudenmeir!

**Comment by Naoray** [comment] 2023-06-30 09:32
@staudenmeir any ETA for a release for this?

**Comment by jurrevanderschaaf** [comment] 2023-06-30 10:20
Can confirm, works great!
Thanks @staudenmeir!

**Comment by staudenmeir** [comment] 2023-07-01 08:44
I released a new version.

**Closed** 2023-07-03 10:19 UTC
